@copy "..\..\..\Bin\Win32\VST\DitherNoiseshaper.dll" "..\..\..\Bin\Win32\VST\Dither & Noiseshaper.dll"
@"..\..\..\Bin\VST-Plugin Unit Test (command line).exe" "..\..\..\Bin\Win32\VST\Dither & Noiseshaper.dll"
@"..\..\..\Bin\VstPluginScreenshotTool.exe" "..\..\..\Bin\Win32\VST\Dither & Noiseshaper.dll"
@move "..\..\..\Bin\Win32\VST\Dither & Noiseshaper.png" "..\..\..\Screenshots\Dither & Noiseshaper.png"
@C:\Progra~1\7-Zip\7z.exe a "..\..\..\Archive\DitherNoiseshaper.7z" "..\..\..\Bin\*\VST\Dither & Noiseshaper*.dll" "..\..\..\Bin\Dither & Noiseshaper.pdf" "..\..\..\Bin\License.txt"
@C:\Progra~1\NSIS\makensis.exe /V2 "..\..\..\Install Scripts\Install Script Dither & Noiseshaper.nsi"
@ftps -s:"..\..\..\Release Scripts\Dither & Noiseshaper.ftp"
@WinSCP -script="..\..\..\Release Scripts\Dither & Noiseshaper.scp"