@copy "..\..\..\Bin\Win32\VST\Audio2MidiTrigger.DLL" "..\..\..\Bin\Win32\VST\Audio2Midi Trigger.DLL"
@"..\..\..\Bin\VST-Plugin Unit Test (command line).exe" "..\..\..\Bin\Win32\VST\Audio2Midi Trigger.DLL"
@"..\..\..\Bin\Win32\VST\VstPluginScreenshotTool.exe" "..\..\..\Bin\Win32\VST\Audio2Midi Trigger.DLL"
@move "..\..\..\Bin\Win32\VST\Audio2Midi Trigger.png" "..\..\..\Screenshots\Audio2Midi Trigger.png"
@7z.exe a "..\..\..\Archive\Audio2MidiTrigger.7z" "..\..\..\Bin\*\VST\Audio2Midi Trigger.dll" "..\..\..\Manuals\Audio2Midi Trigger.pdf" "..\..\..\Bin\License.txt"
@makensis.exe /V2 "..\..\..\Install Scripts\Install Script Audio2Midi Trigger.nsi"
@ftps -s:"..\..\..\Release Scripts\Audio2Midi Trigger.ftp"
@WinSCP -script="..\..\..\Release Scripts\Audio2Midi Trigger.scp"
