@copy "..\..\..\Bin\VST\32-Bit\BarberpoleFlanger.dll" "..\..\..\Bin\VST\32-Bit\Barberpole Flanger.dll"
@"..\..\..\Bin\VST-Plugin Unit Test (command line).exe" "..\..\..\Bin\VST\32-Bit\Barberpole Flanger.dll"
@"..\..\..\Bin\VstPluginScreenshotTool.exe" "..\..\..\Bin\VST\32-Bit\Barberpole Flanger.dll"
@move "..\..\..\Bin\VST\32-Bit\Barberpole Flanger.png" "..\..\..\Screenshots\Barberpole Flanger.png"
@7z a "..\..\..\Archive\BarberpoleFlanger.7z" "..\..\..\Bin\VST\*\Barberpole Flanger.dll" "..\..\..\Manuals\Barberpole Flanger.pdf" "..\..\..\Bin\License.txt"
@makensis /V2 "..\..\..\Install Scripts\Install Script Barberpole Flanger.nsi"
@ftps -s:"..\..\..\Release Scripts\Barberpole Flanger.ftp"
@WinSCP -script="..\..\..\Release Scripts\Barberpole Flanger.scp"