@copy "..\..\..\..\Bin\Win32\VST\NoiseReduction.dll" "..\..\..\..\Bin\Win32\VST\Noise Reduction.dll"
@"..\..\..\..\Bin\VST-Plugin Unit Test (command line).exe" "..\..\..\..\Bin\Win32\VST\Noise Reduction.dll"
@"..\..\..\..\Bin\VstPluginScreenshotTool.exe" "..\..\..\..\Bin\Win32\VST\Noise Reduction.dll"
@move "..\..\..\..\Bin\Win32\VST\Noise Reduction.png" "..\..\..\..\Screenshots\Noise Reduction.png"
@7z a "..\..\..\..\Archive\NoiseReduction.7z" "..\..\..\..\Bin\*\VST\Noise Reduction.dll" "..\..\..\..\Bin\License.txt" "..\..\..\..\Manuals\Noise Reduction.pdf"
@makensis /V2 "..\..\..\..\Install Scripts\Install Script Noise Reduction.nsi"
@ftps -s:"..\..\..\..\Release Scripts\Noise Reduction.ftp"
@WinSCP -script="..\..\..\..\Release Scripts\Noise Reduction.scp"