@copy "..\..\..\..\Bin\VST\32-Bit\NoiseReduction.dll" "..\..\..\..\Bin\VST\32-Bit\Noise Reduction.dll"
@"..\..\..\..\Bin\VST-Plugin Unit Test (command line).exe" "..\..\..\..\Bin\VST\32-Bit\Noise Reduction.dll"
@"..\..\..\..\Bin\VstPluginScreenshotTool.exe" "..\..\..\..\Bin\VST\32-Bit\Noise Reduction.dll"
@move "..\..\..\..\Bin\VST\32-Bit\Noise Reduction.png" "..\..\..\..\Screenshots\Noise Reduction.png"
@7z a "..\..\..\..\Archive\NoiseReduction.7z" "..\..\..\..\Bin\VST\*\Noise Reduction.dll" "..\..\..\..\Bin\License.txt" "..\..\..\..\Manuals\Noise Reduction.pdf"
@makensis /V2 "..\..\..\..\Install Scripts\Install Script Noise Reduction.nsi"
@ftps -s:"..\..\..\..\Release Scripts\Noise Reduction.ftp"
@WinSCP -script="..\..\..\..\Release Scripts\Noise Reduction.scp"